name: borneo_kernel
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # 3rd-party
  event_bus: ^2.0.1
  cancellation_token: ^2.0.1
  logger: ^2.5.0
  coap: ^9.1.0
  cbor: ^6.3.0
  pub_semver: ^2.1.5

  # in this project
  borneo_common:
    path: ../borneo_common
  borneo_kernel_abstractions:
    path: ../borneo_kernel_abstractions

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
