name: borneo_wot
description: Borneo WebThing Implementation
version: 1.0.0
publish_to: none
resolution: workspace
repository: https://github.com/borneo-iot/borneo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # 3rd-party
  event_bus: ^2.0.1
  cancellation_token: ^2.0.1
  logger: ^2.6.0
  coap: ^9.2.0
  cbor: ^6.5.0
  pub_semver: ^2.2.0
  synchronized: ^3.4.0
  retry: ^3.1.2
  polly_dart: ^0.0.7

  # in this project
  borneo_common:
    path: ../borneo_common
  borneo_kernel_abstractions:
    path: ../borneo_kernel_abstractions
  borneo_kernel:
    path: ../borneo_kernel
  lw_wot:
    path: ../lw_wot

dev_dependencies:
  lints: ^6.1.0
  test: ^1.26.0
