name: borneo_wot
description: "BorneoIoT WebThings"
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  cancellation_token: ^2.0.1
  event_bus: ^2.0.1
  pub_semver: ^2.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec