// Mocks generated by Mockito
// This file contains mock implementations for testing purposes

import 'package:borneo_app/features/devices/view_models/device_discovery_view_model.dart';
import 'package:mockito/mockito.dart';
import 'package:borneo_app/core/services/devices/device_manager.dart';
import 'package:borneo_app/core/services/scene_manager.dart';
import 'package:borneo_app/core/services/routine_manager.dart';

// Mock classes for device-related services
class MockDeviceManager extends Mock implements IDeviceManager {}

class MockSceneManager extends Mock implements ISceneManager {}

class MockRoutineManager extends Mock implements IRoutineManager {}

// Mock classes for providers and view models
class MockDeviceDiscoveryViewModel extends Mock implements DeviceDiscoveryViewModel {}

// Factory methods for creating test objects
class TestMocks {
  static MockDeviceManager createDeviceManager() => MockDeviceManager();
  static MockSceneManager createSceneManager() => MockSceneManager();
  static MockRoutineManager createRoutineManager() => MockRoutineManager();
}
