// Mocks generated by Mockito
// This file contains mock implementations for testing purposes

import 'package:mockito/mockito.dart';
import 'package:borneo_app/core/services/devices/device_manager.dart';
import 'package:borneo_app/core/services/scene_manager.dart';
import 'package:borneo_app/core/services/routine_manager.dart';

// Mock classes for device-related services
class MockDeviceManager extends Mock implements DeviceManager {}

class MockSceneManager extends Mock implements SceneManager {}

class MockRoutineManager extends Mock implements RoutineManager {}

// Mock classes for providers and view models
class MockDeviceDiscoveryViewModel extends Mock implements DeviceDiscoveryViewModel {}

class MockSceneEditProvider extends Mock implements SceneEditProvider {}

// Factory methods for creating test objects
class TestMocks {
  static MockDeviceManager createDeviceManager() => MockDeviceManager();
  static MockSceneManager createSceneManager() => MockSceneManager();
  static MockRoutineManager createRoutineManager() => MockRoutineManager();
}
