name: Borneo Firmware CI

on:
  push:
    branches: [master, dev, dev-*]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-ci.yml'
  pull_request:
    branches: [master, dev, dev-*]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-ci.yml'

jobs:
  build-lyfi:
    runs-on: ubuntu-latest
    container: 'espressif/idf:v5.5.2'
    strategy:
      matrix:
        lyfi_product: [bst/ulva6, bst/blc06mk1, bst/c5devkitc1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure git
      run: git config --global --add safe.directory "*"

    - name: Build LyFi Firmware
      working-directory: fw/lyfi
      run: source /opt/esp/idf/export.sh && idf.py build -DPRODUCT_ID=${{ matrix.lyfi_product }} -DCMAKE_BUILD_TYPE=Release