name: Borneo Firmware CI

on:
  push:
    branches: [master, dev, dev-*]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-ci.yml'
  pull_request:
    branches: [master, dev, dev-*]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-ci.yml'

jobs:
  build-lyfi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lyfi_product: [bst/ulva6, bst/blc06mk1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LyFi Firmware in Docker
      run: |
        rm -rf fw/lyfi/build
        docker run -t -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" -w "/app/${{ github.repository }}/fw/lyfi" espressif/idf:v5.5 /bin/bash -c 'git config --global --add safe.directory "*" && idf.py build -DPRODUCT_ID=${{ matrix.lyfi_product }} -DCMAKE_BUILD_TYPE=Release'