name: Borneo Firmware Release CI

on:
  push:
    branches: [master]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-release.yml'
  pull_request:
    branches: [master]
    paths:
      - 'fw/**'
      - '.github/workflows/fw-release.yml'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      LYFI_PRODUCTS: bst/ulva6 bst/blc06mk1 bst/xiaoc3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LyFi Firmware in Docker
      run: |
        mkdir artifacts
        for product in ${{ env.LYFI_PRODUCTS }}; do
          docker run -t \
            -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" \
            -w "/app/${{ github.repository }}/fw/lyfi" \
            espressif/idf:v5.5 \
            /bin/bash -c "rm -rf build && git config --global --add safe.directory '*' && idf.py build -DPRODUCT_ID=$product -DCMAKE_BUILD_TYPE=Release && idf.py merge-bin"
            python fw/scripts/ci/generate_firmware_manifest.py fw/lyfi -o artifacts
        done

    - name: Delete existing release and tag
      run: |
        gh release delete release-fw-latest --yes || true
        git push origin --delete release-fw-latest || true

    - name: Create and push new tag
      run: |
        git tag release-fw-latest
        git push origin release-fw-latest

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-fw-latest
        name: Latest Firmware Release
        draft: false
        files: artifacts/*